### PR TITLE
Add missing DS_PROMETHEUS variable

### PR DESCRIPTION
**Pull request by grembo**
Without it, loading the dashboard fails:

    Failed to upgrade legacy queries Datasource named
    ${DS_PROMETHEUS} was not found

While there, add tag `#freebsd`.

### CODE REVIEW

**Comment by grembo** [comment]
ping?

**Comment by zalegrala** [comment]
@rfmoz @rfrail3 Hi, are you available for review?

**Comment by zalegrala** [comment]
I've forked and will happily take this contribution over at https://github.com/zalegrala/grafana-dashboards
If @rfmoz comes back, we can merge back.

**Comment by rfmoz** [comment]
Thanks for the fix.

**Pull request merged**
